### ISSUE TITLE
Versionamento do `.env.development`

### ISSUE THREAD

**Issue by lucasmonstro** [Br-Dev-Streamers/brdevstreamers-ui#2]
Por razões de segurança eu sugiro que o arquivo `.env.development` não esteja versionado. Sugiro também colocar no `README` uma frase para os próximos desenvolvedores pedirem o `.env.development` para outros developers que já o tiverem.

Cumprimentos @lucasmonstro

**Comment by brunobandev** [comment]
@lucasmonstro retiramos o .env.development e adicionamos no readme como fazer o processo de instalacao. :)
